### ISSUE TITLE
some units (such as nobles) don't have their FLCs show up in game

### ISSUE THREAD

**Issue by floralpond** [Luxor70/EmperorWars#2]
I haven't checked every single unit, but there are a bunch of Nobles on Hazat that have blank FLCs in game. Just the grid shows up. Including the Juan and Karmenia nobles, and also the generic Noble Retinue. There might be other units as well, which I can add here if any pop up.

**Comment by Luxor70** [comment]
Yes, graphics is still a work in progress, but that's only cosmetics
